services:
  - type: web
    name: family-finance
    runtime: docker
    plan: free
    autoDeployTrigger: commit
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: LOG_CHANNEL
        value: stderr
      - key: DB_CONNECTION
        value: pgsql
      - key: APP_KEY
        sync: false
      - key: APP_URL
        sync: false
      - key: DATABASE_URL
        sync: false
